<?php

namespace GFire\CoreBundle\Entity\GeneralLibrary;

use Doctrine\ORM\EntityRepository;

/**
 * TaxExpandedWithheldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxExpandedWithheldRepository extends EntityRepository
{
}
