<?php

namespace GFire\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceAccountEntryOutputVatEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceAccountEntryOutputVatEntryRepository extends EntityRepository
{
}
