<?php

namespace GFire\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FixAssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FixAssetRepository extends EntityRepository
{
}
