<?php

namespace GFire\CoreBundle\Entity\Tax;

use Doctrine\ORM\EntityRepository;

/**
 * FinalWithheldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinalWithheldRepository extends EntityRepository
{
}
